baseURL = "https://misc.dev/"
languageCode = "en-us"
title = "MISC DEV"
theme = "diary"
publishDir = "docs"
googleAnalytics = "UA-165394731-1"
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false